### ISSUE TITLE
Python error when acquiring boot key

### ISSUE THREAD

**Issue by Devcom439** [Endermanch/scripts#5]
#### Description

When attempting to use the SAM Viewer tool, I encountered an `AttributeError` after entering the required LSA key information. The program prompts for the JD, Skew1, GBG, and Data class names, then displays the calculated LSA key. However, an error is raised shortly afterward, stopping execution.

#### Steps To Reproduce

1. Run the following command to initiate SAM Viewer (paths have been modified to protect sensitive information):
`python samviewer.py --reg "path_to\SAM.reg"`

2. Enter each class name (JD, Skew1, GBG, Data) when prompted.

3. After providing the values, the program calculates the LSA key, but then throws an error, as shown below:
```shell
Traceback (most recent call last):
  File "path_to\samviewer.py", line 940, in <module>  
    domain = LMDomain(reg_file=args.reg, jd=args.jd, skew1=args.skew1, gbg=args.gbg, data=args.data, pw=args.pw)
  File "path_to\samviewer.py", line 514, in __init__  
    self.acquire_boot_key(jd, skew1, gbg, data)
  File "path_to\samviewer.py", line 814, in acquire_boot_key
    self.fd.key.data[:self.fd.key.datalength],
AttributeError: 'NoneType' object has no attribute 'key'
```

#### Expected Behavior
After entering the LSA key components, the program should proceed without any errors.

#### Actual Behavior
The program encounters an `AttributeError`, which suggests that `self.fd` is `None` when `acquire_boot_key `tries to access `self.fd.key`.

#### Environment
OS: Windows 11
Python version: Python 3.12.4

#### Full output (`...` is something I left out)
PS ...\scripts> python .\sam\samviewer.py --reg "...\SAM Viewer\SAM.reg"
⚠️ The system boot key is required to decrypt the password hashes.
The boot key is calculated using the following formula:
        B = JD[c] || Skew1[c] || GBG[c] || Data[c],
where:
• || is a concatenation operator
• c is the registry key class name (❗ hidden away in the Registry Editor)
• JD, Skew1, GBG, and Data are LSA subkeys

To acquire the boot key class name components, you have to navigate to:
        HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa
of the target system and literally PRINT the LSA key to PDF.

Hit Ctrl+P, select «Microsoft Print to PDF», and save the file.
Then, open the PDF, find the JD, Skew1, GBG, and Data class names, and enter them below.
Each class name is a 4-byte hex value (8 characters), together composing a 16-byte Base16 encoded string.

Example PDF entry:
        Key Name: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\JD
        Class Name: 37557b3a ← this is what you need ❗
        Value 0
          Name: Lookup
          Type: REG_BINARY
          Data:
        00000000 25 9d f2 f8 59 27

⚠️ JD class name is missing.
Enter JD class name: ...
⚠️ Skew1 class name is missing.
Enter Skew1 class name: ...
⚠️ GBG class name is missing.
Enter GBG class name: ...
⚠️ Data class name is missing.
Enter Data class name: ...
LSA key:
🔑 ...

Traceback (most recent call last):
  File "...\scripts\sam\samviewer.py", line 940, in <module>  
    domain = LMDomain(reg_file=args.reg, jd=args.jd, skew1=args.skew1, gbg=args.gbg, data=args.data, pw=args.pw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\scripts\sam\samviewer.py", line 514, in __init__  
    self.acquire_boot_key(jd, skew1, gbg, data)
  File "...\scripts\sam\samviewer.py", line 814, in acquire_boot_key
    self.fd.key.data[:self.fd.key.datalength],
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'key'
PS ...\scripts>

**Comment by LolekLiam** [comment]
Your SAM.reg probably has the wrong paths inside, because you were probably exporting from a loaded sam hive under a different name. Just use find and replace in notepad to replace `[HKEY_LOCAL_MACHINE\yoursam\` with `[HKEY_LOCAL_MACHINE\SAM\`. That should fix it.

**Comment by blustri** [comment]
mine still has this issue, even  though its the correct path. any help?
